### PR TITLE
Backport changes from 18.1 to 17.1

### PR DESCRIPTION
**Pull request by Flamefire**
I'd like to use LOS 17.1 with the XZ1C due to e.g. the stock camera. 

These are cherry-picks which are required for https://github.com/whatawurst/android_device_sony_lilac/pull/29 and https://github.com/whatawurst/android_vendor_sony_lilac/pull/15. Some where directly required due to changes in those other repos/PRs, other were required to avoid conflicts.

I'm currently building this but if you could have a look if all looks sane and tell me if you are interested in merging this it would be greatly  appreciated!

Edit: Build succeeded. Test on device successfully running for weeks

### CODE REVIEW

**Comment by derfelot** [comment]
Hi there,

sorry, been a bit busy recently. I'll review this (and the other PR's) during the weekend and let you know :)

**Comment by shank03** [comment]
Why not just use 17.1 branch ? O_o

**Comment by Flamefire** [comment]
@shank03 17.1 is not updated anymore once 18.1 has started. So I want to include the new things from 18.1 in 17.1.
I also need to keep the 3 repos in sync, e.g. the changes in https://github.com/whatawurst/android_device_sony_lilac/pull/29 require these changes here.

I'm planning to backport more from yoshino common 18.1, especially the fixes to the IMS/XperiaParts stuff which fix the missing connectivity after first boot. This 3 PRs are just the start and meant to get the 17.1 branches in the other 2 repos to the state of the 18.1 branches so I can use more from yoshino-common later without worrying about e.g. the partition size changes breaking something

**Comment by Flamefire** [comment]
I tried this on my device and it seemingly works (as expected)

I'm adding (and testing) the PRs by @shank03 regarding the CS/XperiaTools: #22, #23, #25, #39
Also the OCS and APN commits from #21 which seem relevant and related.

Marking this as ready now, and will update the branch later once I tested the mentioned PRs on top of this. You can merge already if you like, then I'll create a new PR with just those changes.

If there is anything else you remember being particularly worth backporting then please let me know. I've seen an update to LLVM which I'll include expecting a bit better optimizations.

**Comment by petefoth** [comment]
If it's any help, I have just made an unofficial /e/OS ROM build using @Flamefire's branch. It built OK and seems to be running fine with no problems.
Let me know if there are any specific things you would like me to test

**Comment by Flamefire** [comment]
Using my clones for the 17.1 builds now. Hence closing.
Tracking the 18.1 changes there, so keep up the great work!

**Pull request closed without merging**
