### PR TITLE
NetworkSwitcher: Handle unlocked phone before switching networks

### LINKED ISSUE #51: Network switcher does not switch back after unlock
There is a race condition in the network switcher:

- Network switcher delays next actions
- User unlocks phone
- Network switcher switches to 3G and registers listener for ACTION_USER_UNLOCKED as `isFileEncryptedNativeOrEmulated` is set

-> Network stays at 3G forever

@shank03 What exactly is that encrypted check protecting? Is there another way to check if that is available yet?

Solutions I can think of:
- Register receiver in create and set bool if unlocked, this can then be checked skipping the wait for unlock part
- Check if already unlocked, depends on what it is required for. https://github.com/aosp-mirror/platform_packages_apps_settings/blob/060bf953e39b3310c04a0440acf702aeb691207c/src/com/android/settings/deviceinfo/StorageWizardMigrateConfirm.java#L101-L102 could maybe be used here?

### PR DESCRIPTION
**Pull request by Flamefire**
When the phone is unlocked before we register the unlock-receiver the network is never switched back.
To avoid this register a receiver on start to receive the unlock event and check for that.

@shank03 Please check this.

Fixes #51

### CODE REVIEW

**Comment by shank03** [comment]
I think this needs to be more specific of what scenario you are trying to address ?

I see that this is needed when, let's say, user has no lock screen ?

Because no user can unlock device in less than 1.4 sec (after reboot) except for the scenario mentioned above (or when user have very small password).

**Comment by shank03** [comment]
I suspect there gonna be a need of line to line code discussion.. let me know if you are comfortable for a meet (google meet).

**Comment by Flamefire** [comment]
If the user has no lock screen, won't `isFileEncryptedNativeOrEmulated` return False anyway?

> Because no user can unlock device in less than 1.4 sec

I'd say unlocking is certainly possible in lass than a second, but that is not the issue: We register observers at various times: 
- SubIdObserver
- SlotObserver

So there can (and in my case was) a considerable delay. I noticed e.g. that the lock screen came up (way) before the SIM PIN screen came up.
So I think that was the issue here.

No issues with Google meet or whatever as long as it works in a browser. If maybe the above already clears things up enough than you could also use the comment tools of github on the changed lines.

**Comment by shank03** [comment]
Okay I see here, I missed the SIM PIN scenario.

Thank you for pointing it out :)

Well then, @derfelot ready to merge this.

**Comment by Flamefire** [comment]
Ok, great! Thanks for checking. :)
Not too familiar with that stuff so could have easily missed something.

**Comment by derfelot** [comment]
Thanks, merging. Could someone add this to the https://github.com/whatawurst/OpenCustomizationSelector repo as well? IIRC you have merge rights there @shank03

**Pull request merged**
