### PR TITLE
yoshino-common: general clean up

### PR DESCRIPTION
**Pull request by linckandrea**
Some clean up commits + necessary commit for improve stability with Gcam

### CODE REVIEW

**Comment by linckandrea** [comment]
DNM, i'll keep pushing more clean up commits

**Comment by linckandrea** [comment]
ready to be tested

**Comment by shank03** [comment]
Umm.. why gcam ? Any reason or just an addition ?

**Comment by linckandrea** [comment]
just a small addition

**Comment by cryptomilk** [comment]
LGTM

**Pull request merged**
